qdm12/gluetun

- portforward.sh
> Fix portforward script syntax error

- Dockerfile
- README.md
So that the PIA logs match user's timezone.
> Added tzdata so that users can set timezone via TZ var

- .github/workflows/dockerhub-description.yml
- .github/workflows/misspell.yml
- .github/workflows/security.yml
- Dockerhub description disabled
- Security scans only run on push to master branch
- Misspell workflow only run on master branch push and PRs
> Revise workflows

- Dockerfile
- README.md
- cmd/main.go
- internal/params/params.go
- internal/params/shadowsocks.go
- internal/settings/shadowsocks.go
- internal/shadowsocks/conf.go
- internal/shadowsocks/conf_test.go
- internal/shadowsocks/shadowsocks.go
> SHADOWSOCKS_METHOD environment variable

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/help.md
- .github/workflows/misspell.yml
- action-misspell fix
- Issue templates improved
> Workflows adjustments

- Dockerfile
- internal/cli/cli.go
Refers to #133 
I will test it in the coming days to ensure it works as expected and don't get blocked / throttled.
> Better healthcheck

- cmd/resolver/main.go
- Change domain to privacy.network
> Feature request: Support new PIA servers #216

- README.md
- cmd/gluetun/main.go
- internal/cli/cli.go
- internal/constants/splash.go
- internal/openvpn/loop.go
- internal/params/params.go
- internal/params/updater.go
- internal/server/server.go
- internal/settings/settings.go
- internal/updater/cyberghost.go
- internal/updater/loop.go
- internal/updater/nordvpn.go
- internal/updater/options.go
- internal/updater/pia.go
- internal/updater/purevpn.go
- internal/updater/surfshark.go
- internal/updater/updater.go
- internal/updater/vyprvpn.go
- internal/updater/windscribe.go
> Updater loop with period and http route

- cmd/gluetun/main.go
- internal/dns/loop.go
- internal/openvpn/loop.go
- internal/publicip/loop.go
- internal/server/server.go
- internal/shadowsocks/loop.go
- internal/tinyproxy/loop.go
- internal/updater/loop.go
Just some maintenance in the main.go file, improving the wait mechanism for when the program shuts down.
> Revisit waitgroup

- Dockerfile
- README.md
- internal/models/selection.go
- internal/params/openvpn.go
- internal/params/params.go
- internal/provider/mullvad.go
- internal/settings/openvpn_test.go
- internal/settings/providers.go
> Disable ipv6 for Mullvad

- README.md
- cmd/gluetun/main.go
- internal/cli/cli.go
- internal/constants/paths.go
- internal/constants/splash.go
- internal/logging/duration.go
- internal/logging/duration_test.go
- internal/models/selection.go
- internal/openvpn/loop.go
- internal/provider/cyberghost.go
- internal/provider/mullvad.go
- internal/provider/nordvpn.go
- internal/provider/pia.go
- internal/provider/piav3.go
- internal/provider/piav4.go
- internal/provider/provider.go
- internal/provider/purevpn.go
- internal/provider/surfshark.go
- internal/provider/utils.go
- internal/provider/vyprvpn.go
- internal/provider/windscribe.go
- internal/routing/reader.go
- internal/routing/reader_test.go
- internal/routing/routing.go
- internal/settings/providers.go
- internal/version/version.go
Still a work in progress, should be done in the coming days.
Thanks to @willhowlett for pointing me in the right direction.
Refers to #236
> PIA nextgen portforward

- Dockerfile
- README.md
- cmd/gluetun/main.go
- internal/params/firewall.go
- internal/params/params.go
- internal/settings/firewall.go
> FIREWALL_INPUT_PORTS environment variable

- internal/provider/purevpn.go
> Fix PureVPN

- internal/provider/windscribe.go
> Fix TLS keys out of sync for Windscribe

- internal/updater/cyberghost.go
- internal/updater/privado.go
- internal/updater/purevpn.go
- internal/updater/resolver.go
- internal/updater/resolver_test.go
- internal/updater/surfshark.go
- internal/updater/vyprvpn.go
I'll update server information constants in a separate pull request once this one is merged. (done)
> Feature: updater changes to have more VPN IP addresses

- .github/ISSUE_TEMPLATE/provider.md
- Dockerfile
- internal/configuration/openvpn.go
- internal/configuration/openvpn_test.go
- internal/openvpn/custom.go
- internal/openvpn/loop.go
> Custom Openvpn configuration file

- internal/firewall/enable.go
- internal/routing/reader.go
Implementing feedback from #413 and restricting route listing to IPv4 from #418
> Implementing PR feedback and restricting route listing to IPv4 only

- Dockerfile
- internal/provider/piav4.go
- internal/provider/piav4_test.go
- Update PIA token URL
- Change base64 decoding to standard decoding
- Add unit tests
- Remove environment variable `GODEBUG=x509ignoreCN=0`
- Fixes #423 
- Fixes #292 
- Closes #264 
- Closes #293
> Fix PIA port forwarding

- cmd/gluetun/main.go
- internal/healthcheck/health.go
- internal/healthcheck/server.go
- internal/openvpn/loop.go
> Restart Openvpn when the container is unhealthy

- cmd/gluetun/main.go
- internal/healthcheck/health.go
- internal/healthcheck/server.go
- internal/openvpn/loop.go
- See #417 
- Re-merging due to bad forced push
> Restart unhealthy (#417)

- internal/constants/servers.json
- internal/constants/servers_test.go
- internal/models/openvpn.go
- internal/models/server.go
- internal/provider/windscribe/connection.go
- internal/provider/windscribe/openvpnconf.go
- internal/updater/providers/windscribe/api.go
- internal/updater/providers/windscribe/servers.go
> Add verify-x509-name to Windscribe Openvpn config

- internal/storage/servers.json
Hello, 
I had some troubles in connecting to LA / Chicago servers on FastestVPN, so I have updated the servers list.
Please let me know if I should do Pull Requests whenever I notice that some servers updates are needed, or if I should just report it to you. 
Thanks
> updated FastestVPN servers

- .github/workflows/ci.yml
Fulfills #688 
need to make package public after first build/push. I'm not sure if you also need to enable packges/container registry on your account/repo
> add ghcr image

- internal/provider/slickvpn/connection.go
- internal/provider/slickvpn/openvpnconf.go
- internal/provider/slickvpn/updater/servers.go
- internal/storage/servers.json
> SlickVPN fixes

- internal/provider/vpnunlimited/openvpnconf.go
> fix(vpnunlimited): lower TLS security level to 3

- Dockerfile
- internal/configuration/settings/portforward.go
- internal/configuration/sources/env/portforward.go
- internal/vpn/run.go
- Defaults to current provider in use
- Can be chosen from a list of providers with custom code implemented
Suggested in #1488
> feat(pf): `VPN_PORT_FORWARDING_PROVIDER` variable

- internal/publicip/ipinfo/fetch.go
https://github.com/qdm12/gluetun/issues/1838
https://github.com/qdm12/gluetun/issues/1700
> Fixed IPv6 endpoint for ipinfo

- internal/provider/purevpn/updater/servers.go
https://support.purevpn.com/purevpn/openvpn-files
> Update purevpn's zip file url based on

- README.md
- internal/configuration/settings/portforward.go
- internal/portforward/interfaces.go
- internal/portforward/service/interfaces.go
- internal/portforward/service/start.go
- internal/provider/perfectprivacy/portforward.go
- internal/provider/perfectprivacy/portforward_test.go
- internal/provider/utils/portforward.go
- internal/routing/default.go
- internal/routing/ip.go
- internal/routing/local.go
> feat(perfectprivacy): port forwarding support

- .github/ISSUE_TEMPLATE/bug.yml
- .github/labels.yml
- README.md
- internal/configuration/settings/openvpnselection.go
- internal/constants/providers/providers.go
- internal/models/markdown.go
- internal/provider/giganews/connection.go
- internal/provider/giganews/openvpnconf.go
- internal/provider/giganews/provider.go
- internal/provider/giganews/updater/filename.go
- internal/provider/giganews/updater/hosttoserver.go
- internal/provider/giganews/updater/resolve.go
- internal/provider/giganews/updater/servers.go
- internal/provider/giganews/updater/updater.go
- internal/provider/providers.go
> feat(providers): add giganews support

- README.md
"swiss-knife-like" changed to "swiss-army-knife-like"
sorry for my OCD lol.
> optional update on README.md.
