qdm12/gluetun

- entrypoint.sh
A new set of IP addresses is appended on each restart of the container which eventually results in the openvpn error `Maximum number of 'remote' options (64) exceeded.`
> Don't insert duplicate ip addresses to the openvpn config file

- Dockerfile
- README.md
- portforward.sh
When running this container in a Kubernetes pod, it is not possible to directly mount the `/forwarded_port` file from other containers in the pod.
Normally this can be accomplished by creating a shared volume, and mounting this volume in all required containers. Because this container writes the file to `/` by default, it is currently impossible to use this technique, as it would try to mount the given volume on the root filesystem.
This pull request makes the folder in which the file is written configurable, so that a subfolder of the root filesystem can be used.
> Make forwarded_port file location configurable

- Dockerfile
- README.md
- docker-compose.yml
- entrypoint.sh
- shadowsocks.json
- Supports DNS queries
- Can tunnel both UDP and TCP system wide
- Clients are available on all platforms: linux, android, windows, etc.
> Shadowsocks proxy built-in, fixes #30

- .dockerignore
- .travis.yml
- Dockerfile
- README.md
- ci.sh
- hooks/build
- hooks/post_build
After some long hours of tearing my neurons apart, there we are, we finally have a pipeline building Docker image for *all* CPU architectures (intel, amd, ibm, arm, etc.). What's even more exciting? You can simply `docker pull` the image without even specifying the architecture in the Docker tag, Docker will automatically select and pull the right image for you! Enjoy!!
Thanks to @yacht7 and @gurabli for helping out on Slack.
> Building Docker images for all CPU architectures

- .github/workflows/buildx-branch.yml
- Dockerfile
- README.md
- docker-compose.yml
- internal/params/pia.go
For clearer environment variables, especially since:
- it only applies to PIA (not Mullvad nor Windscribe)
- `CIPHER_ALGORITHM` and `AUTH_ALGORITHM` environment variables will be added next in #94 
The `ENCRYPTION` environment variable is still valid for retro compatibility.
> Rename ENCRYPTION to PIA_ENCRYPTION

- cmd/main.go
Refers to #140, #50  and PR #126 
You should be able to try the corresponding image with tag `:restart`
> Restarts openvpn on failure without Docker restart

- README.md
It looks like the readme had a few copy/paste errors. And... as opposed to what the readme claims the shadowsocks and tinyproxy servers are not started by default ;)
> Updated readme to match the Dockerfile

- Dockerfile
- README.md
- cmd/gluetun/main.go
- docker-compose.yml
- internal/cli/cli.go
- internal/constants/servers.go
- internal/constants/servers_test.go
- internal/constants/splash.go
- internal/models/server.go
- internal/models/servers.go
- internal/openvpn/loop.go
- internal/provider/cyberghost.go
- internal/provider/mullvad.go
- internal/provider/nordvpn.go
- internal/provider/pia.go
- internal/provider/provider.go
- internal/provider/purevpn.go
- internal/provider/surfshark.go
- internal/provider/vyprvpn.go
- internal/provider/windscribe.go
- internal/storage/merge.go
- internal/storage/storage.go
- internal/storage/sync.go
Written to `/gluetun/servers.json` and merged with hardcoded constants on a provider+timestamp based priority.
First step for #218 , #216, #225 
Next step is to move code around to allow users to update the servers themselves if they want to.
> Persistent server pools

- cmd/gluetun/main.go
- internal/cli/cli.go
- internal/firewall/enable.go
- internal/firewall/firewall.go
- internal/firewall/vpn.go
- internal/openvpn/loop.go
- internal/provider/cyberghost.go
- internal/provider/mullvad.go
- internal/provider/nordvpn.go
- internal/provider/pia.go
- internal/provider/piav3.go
- internal/provider/piav4.go
- internal/provider/provider.go
- internal/provider/purevpn.go
- internal/provider/surfshark.go
- internal/provider/utils.go
- internal/provider/vyprvpn.go
- internal/provider/windscribe.go
- From now only a single OpenVPN connection is written to the OpenVPN configuration file
- If multiple connections are matched given the user parameters (i.e. city, region), it is picked at pseudo random using the current time as the pseudo random seed.
- Not relying on Openvpn picking a random remote address, may refer to #229 
- Program is aware of which connection is to be used, in order to use its matching CN for port forwarding TLS verification with PIA v4 servers, see #236 
- Simplified firewall mechanisms
> Single connection written to openvpn configuration

- Dockerfile
- README.md
- internal/provider/piav4.go
- Returns an error if the server does not support port forwarding
- TLS verification using the server common name obtained through the API
- Updated readme
- Fixes #236
> PIA port forwarding final fixes

- internal/httpproxy/accept.go
- internal/httpproxy/auth.go
- internal/httpproxy/handler.go
- Only accepts HTTP 1.x protocols
- Only checks the credentials when the method is `CONNECT` or the request URL is absolute
- More logging on authorization failures
- Removes the authorization headers before forwarding the HTTP(s) requests
- Refers to #298
> HTTP proxy authentication problems

- internal/httpproxy/handler.go
Thanks for your work on this nice project.
When using the http proxy, it looked like the http redirect was handled by the proxy instead of the browser.
This PR tries to fix it.
When browsing to a **http** website the redirect is followed by the http proxy (Go) and the body of the **https** page is returned instead of the redirect (Statuscode 301).
Example of current situation:
```
curl -vvv -x proxy:8118 http://google.com
> GET http://google.com/ HTTP/1.1
....
< HTTP/1.1 200 OK
...
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en-GB"><head>...<title>Google</title>...
````
The default behaviour of the Golang http.Client is following redirects. By configuring a redirect function that always returns a
`ErrUseLastResponse`, the redirect will be returned to the …
> Return the response of a redirect, do not follow.

- cmd/gluetun/main.go
- internal/firewall/enable.go
- internal/firewall/firewall.go
- internal/routing/reader.go
- internal/routing/routing.go
We cover all links that have their encapsulation set to 'ether' (in my testing this equated to all eth0/eth1/eth2/etc).
My assumption here is we'll be executing inside a docker container, and docker networks are exposed under eth0/eth1/etc, the openvpn tunnel and the local loopback don't have this so we automatically exclude them!
I think I've got it right, but haven't tested it yet (that's next), just raising now for any feedback/direction.
Fixes #411 
Cheers!
> Uplift the 'localSubnet' concept to cover all local ethernet interfaces

- internal/firewall/enable.go
- internal/firewall/firewall.go
- internal/firewall/ip6tables.go
- internal/firewall/iptables.go
- internal/firewall/iptablesmix.go
- Feature/Bugfix: Block all IPv6 traffic with `ip6tables` by default
- Feature: Adapt existing firewall code to handle IPv4 and IPv6, depending on user inputs and environment
- Maintenance: improve error wrapping in the firewall package
> Feature/Bugfix: IPv6 blocking

- Dockerfile
- cmd/gluetun/main.go
- internal/configuration/log.go
- internal/configuration/settings.go
- internal/configuration/settings_test.go
> `LOG_LEVEL` variable

- README.md
container_name is required to correctly refer to gluetun container from a different compose file
> add line to compose example

- README.md
This PR is a very small PR updating the README in the refactoring date from YYYY-DD-MM to the more standard YYYY-MM-DD
> docs(readme): Update announcement date in README to be ISO standard

- internal/provider/privateinternetaccess/portforward.go
Connection to PIA using OpenVPN worked fine, but getting a token for the port forwarding service resulted in HTTP errors.
Looking at the [latest official shell script to get a token](https://github.com/pia-foss/manual-connections/blob/9b42ad934a9353fbefda7cbab2725f4f3b1850a3/get_token.sh#L72) it seems that the token URL and method have changed. This PR adjusts gluetun to match.
Note: this is my first time writing/using Go.
> fix(privateinternetaccess): fix getting token for port forwarding

- internal/firewall/enable.go
- internal/firewall/iptables.go
- internal/firewall/iptablesmix.go
- internal/routing/default.go
- internal/routing/ip.go
- internal/routing/local.go
- internal/wireguard/netlink_integration_test.go
- internal/wireguard/rule.go
- internal/wireguard/rule_test.go
- internal/wireguard/run.go
Enable ipv6 connection to Wireguard VPN servers & tunneling for IPv6 addresses.
There's still things to be done such as:
-  use IPv6 by default and fallback to IPv4 if not functioning.
- check if IPv6 is enabled on host before attempting to contact an IPv6 server
Fixes #154 
Might help #594
> Enable ipv6 connection & tunneling

- internal/provider/fastestvpn/updater/servers.go
I hope this will update fastestvpn servers in servers.json and config files. right now i am not able to use fastestvpn with gluetun.
Updater throws below error. I realized the url is not live anymore. i got the working url from fastestvpn support.
> updating fastestvpn servers

- internal/provider/ipvanish/updater/servers.go
- internal/provider/ipvanish/updater/servers_test.go
> fix: ipvanish zip location

- README.md
I'm proposing the addition of `UPDATER_PERIOD` and `UPDATER_VPN_SERVICE_PROVIDERS` to the [docker-compose example](https://github.com/qdm12/gluetun#setup) in the README to prevent the issue described in the discussion linked below. This will help bring awareness to the static list of servers that are shipped with each release and prevent connection issues when the IPs in the user's selected region(s) have become stale and there's no clear indicator given to the users to direct them to updating their local servers.json file. Knowing that releases can happen daily or bi-annually and the updater is disabled by default, I feel this is probably a no-brainer to prevent others, especially new users, from running into the same issue.
https://github.com/qdm12/gluetun/discussions/1356#discussioncomm …
> Add updater vars to docker-compose example

- internal/configuration/sources/secrets/httpproxy.go
Error message reading secret file for http proxy password wrongly refer to openvpn instead of http proxy
> Update httpproxy.go to fix error message

- internal/provider/protonvpn/portforward.go
This fixes an issue in #1543 where the returned port will always be zero.
Built this locally and made sure the port was now correctly assigned:
```
gluetun-vpn_gateway-1  | 2023-06-01T20:23:34-07:00 INFO [port forwarding] port forwarded is 42757
gluetun-vpn_gateway-1  | 2023-06-01T20:23:34-07:00 INFO [firewall] setting allowed input port 42757 through interface tun0...
gluetun-vpn_gateway-1  | 2023-06-01T20:23:34-07:00 INFO [port forwarding] writing port file /tmp/gluetun/forwarded_port
```
I also used netcat to make sure both UDP and TCP was properly forwarded.
> Fix ProtonVPN port forwarding assigning port zero

- go.mod
- go.sum
- internal/mod/info.go
- internal/mod/load.go
- internal/mod/probe.go
- internal/netlink/wireguard.go
- First check if the wireguard family exists
- If not, try loading the wireguard kernel module
- If it succeeds, re-check the wireguard family exists
> fix(wireguard): load Wireguard module if needed

- internal/configuration/sources/env/serverselection.go
Found a typo while fixing #2070, seems like `STREAM_ONLY` env set `MultihopOnly` flag while it should set `StreamOnly`.
> fix: STREAM_ONLY env should set StreamOnly flag for server selection

- Dockerfile
- internal/configuration/settings/serverselection.go
- internal/configuration/sources/env/serverselection.go
- internal/provider/utils/filtering.go
- internal/provider/utils/filtering_test.go
- internal/storage/filter.go
Was in TODO per comment in code, so I took freedom to implement this. It adds another env PORT_FORWARD_ONLY which will filter for servers supporting port forwarding. This works only for PIA, I presume, so I locked this to only PIA support. Cases like #2048 could be mitigated with this PR merged and this settings on.
> feat: add PORT_FORWARD_ONLY env to filter for servers with port forwarding

- Dockerfile
- internal/configuration/sources/secrets/helpers.go
- internal/configuration/sources/secrets/vpn.go
- internal/configuration/sources/secrets/wireguard.go
Currently docker secrets aren't supported for wireguard environment variables, but should.
> feat(settings): load wireguard inidivual fields as secret files

- .golangci.yml
- Dockerfile
- internal/configuration/settings/errors.go
- internal/configuration/settings/serverselection.go
- internal/configuration/settings/validation/servers.go
- internal/configuration/sources/env/serverselection.go
- internal/models/filters.go
- internal/models/markdown.go
- internal/models/server.go
- internal/provider/nordvpn/updater/models.go
- internal/provider/nordvpn/updater/servers.go
- internal/provider/utils/filtering.go
- internal/provider/utils/filtering_test.go
- internal/storage/choices.go
- internal/storage/filter.go
- internal/storage/formatting.go
Aims to fix #1643 
I am _not_ a GO developer, please read this code carefully!
After talking to NordVPN support, as long as a server supports P2P, a P2P connection will be established once it's determined there is a need for it (IE seeing P2P traffic). There's no way of knowing if it has connected to the P2P server other than contacting support with the IP address or results from `curl https://ipleak.net/json/`. I did ask if there was a way of starting the connection and specifying P2P from the get-go to avoid any switching but they said there was no documentation on this.
I've also [seen online](https://www.reddit.com/r/nordvpn/comments/q6astb/comment/hgbawxq/) that this switch from standard to P2P can result in you being reconnected to a "better" server, but this could also introduce …
> Category filtering for NordVPN

- README.md
- internal/configuration/settings/provider.go
- internal/configuration/settings/wireguard.go
- internal/configuration/settings/wireguardselection.go
- internal/models/markdown.go
- internal/models/markdown_test.go
- internal/provider/fastestvpn/connection.go
- internal/provider/fastestvpn/updater/hosttoserver.go
- internal/provider/fastestvpn/updater/servers.go
Credits to:
- @Zerauskire for the initial investigation
- @jvanderzande for an initial implementation as well as reviewing this pull request
> feat(fastestvpn): support for Wireguard

- README.md
- internal/configuration/settings/provider.go
- internal/configuration/settings/wireguard.go
- internal/configuration/settings/wireguardselection.go
- internal/models/connection.go
- internal/models/markdown.go
- internal/provider/protonvpn/connection.go
- internal/provider/protonvpn/updater/api.go
- internal/provider/protonvpn/updater/iptoserver.go
- internal/provider/protonvpn/updater/servers.go
Image is `qmcgaw/gluetun:pr-2390`
You can use it by using `VPN_SERVICE_PROVIDER=protonvpn`, `VPN_TYPE=wireguard`, and then set  `WIREGUARD_PRIVATE_KEY`.
> feat(protonvpn): Wireguard support

- cmd/gluetun/main.go
- internal/cli/openvpnconfig.go
- internal/configuration/settings/interfaces.go
- internal/configuration/settings/provider.go
- internal/configuration/settings/serverselection.go
- internal/configuration/settings/settings.go
- internal/configuration/settings/vpn.go
- internal/server/vpn.go
- Disallow setting a server filter when there is no choice available
- Allow setting an invalid server filter when there is at least one choice available
- Log at warn level when an invalid server filter is set
- Fix #2337
> feat(config): allow invalid server filters

- internal/configuration/settings/serverselection.go
- internal/provider/privateinternetaccess/portforward.go
> fix(pia): support port forwarding using Wireguard

- internal/server/middlewares/auth/apikey.go
- internal/server/middlewares/auth/configfile_test.go
- internal/server/middlewares/auth/lookup.go
- internal/server/middlewares/auth/settings.go
> feat(server): add apikey auth method

- internal/server/middlewares/auth/basic.go
- internal/server/middlewares/auth/lookup.go
- internal/server/middlewares/auth/settings.go
-  Add basic http auth to vpn/settings  & openvpn/settings routes.
- Get username and password from environment variables.
- Sets a default username and password.
Partly fixes #2238 
@qdm12 , please provide feedback.
Do we need a default username and password.
I have added basic auth only for the /settings route so that breakage with existing users are minimal.
Edit:
Original PR is updated to use the new auth middleware. Above points are no longer valid.
See #2238 , #2434
> feat(control server authentication): add basic http auth

- internal/publicip/api/api.go
- internal/publicip/api/cloudflare.go
- internal/publicip/api/errors.go
Note that the Cloudflare API does not seem to support returning info for arbitrary IP addresses (only the caller's public IP), so it can't be used with calls to FetchMultiInfo, but since this is only used in the context of a couple of VPN providers currently, it may not be a significant limitation.
> feat(publicip): add Cloudflare support

- internal/publicip/api/api.go
- internal/publicip/api/api_test.go
- internal/publicip/api/echoip.go
- option to specify a `echoip#https://xyz` url in `PUBLICIP_API`
- ifconfig.co implementation now uses echoip implementation
- fixes #2510 
Image tag: `:pr-2529`
> feat(publicip): support custom API url `echoip#https://...`

- internal/wireguard/rule.go
Related to #2521 #2471 and #1991
Considers the `file exists` error as a success for adding an IP rule.
Run with image tag `:pr-2526`
> fix(wireguard): add ivp6 rule
